# Generated by Django 2.1.4 on 2018-12-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchant_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmerchant',
            name='account_number',
            field=models.CharField(max_length=100),
        ),
    ]
